#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <fstream>
#include <iostream>
#include <chrono>
#include <vector>
#include <filesystem>
#include <random>
#include <algorithm>
#include <unordered_map>
#include <omp.h>

#include "kbsa_core.hpp"
#include "kbsa_merge.hpp"
#include "kbsa_params.hpp"
#include "kbsa_anchor.hpp"
#include "kbsa_rank.hpp"
#include "kbsa_unitig.hpp"
#include "kbsa_unitig_score.hpp"
#include "kmc_runner.h"

namespace fs = std::filesystem;

using namespace kbsa;

struct Options
{
  std::string bulk1_db;
  std::string bulk2_db;
  std::string bulk1_hist;
  std::string bulk2_hist;
  std::string output;
  double kai_min {0.0};
  double g_min {0.0};
  double error_rate {0.005};
};

void print_usage(const char* prog)
{
  fprintf(stderr,
    "kbsa - BSA-seq kmer scoring (KMC-only, standalone)\n\n"
    "Usage: %s score --bulk1 <db> --bulk2 <db> \\\n"
    "                      --bulk1-hist <hist.txt> --bulk2-hist <hist.txt> \\\n"
    "                      -o <output.tsv> [options]\n\n"
    "Options:\n"
    "  --kai-min <float>    Min kai_reg for emission gate (default: 0.0; emit all)\n"
    "  --g-min <float>      Min G-test score for emission gate (default: 0.0; emit all)\n"
    "  --error-rate <float> Error rate for epsilon (default: 0.005)\n\n"
    "Input: KMC databases (bulk1_db.kmc_pre/suf, bulk2_db.kmc_pre/suf)\n"
    "       Generated by: kmc -k31 -ci1 -cs65535 @input.lst db_name tmp/\n"
    "       Histograms by: kmc_tools transform db histogram hist.txt\n\n"
    "Output: TSV with columns:\n"
    "  kmer  significance  kai_reg  g_score  z_score  bulk2_raw  bulk1_raw  bulk2_adj  bulk1_adj\n"
    "  significance: BULK1 (kai<0.5) or BULK2 (kai>=0.5); direction is intrinsic.\n"
    "  z_score: signed sqrt(g_score); + means BULK2-enriched, - means BULK1-enriched.\n",
    prog);
}

struct CountOptions
{
  std::vector<std::string> bulk1_files;
  std::vector<std::string> bulk2_files;
  std::string output_dir;
  uint32_t k {31};
  uint32_t threads {20};
  uint32_t mem_gb {16};
  uint64_t ci {2};
  uint64_t cs {65535};
  bool only_bulk1 {false};
  bool only_bulk2 {false};
};

void print_count_usage(const char* prog)
{
  fprintf(stderr,
    "kbsa count - KMC k-mer counting (integrated)\n\n"
    "Usage: %s count --bulk1 <R1.fq.gz> [R2.fq.gz ...] \\\n"
    "                      --bulk2 <R1.fq.gz> [R2.fq.gz ...] \\\n"
    "                      -o <output_dir> [options]\n\n"
    "Options:\n"
    "  -k <int>       K-mer length (default: 31)\n"
    "  -t <int>       Threads (default: 20)\n"
    "  -m <int>       Max RAM in GB (default: 16)\n"
    "  --ci <int>     Min k-mer count cutoff (default: 2)\n"
    "  --cs <int>     Max counter value (default: 65535)\n\n"
    "Output:\n"
    "  <output_dir>/bulk1_db.kmc_pre/suf  Bulk1 pool KMC database\n"
    "  <output_dir>/bulk2_db.kmc_pre/suf  Bulk2 pool KMC database\n"
    "  <output_dir>/bulk1_hist.txt        Bulk1 histogram\n"
    "  <output_dir>/bulk2_hist.txt        Bulk2 histogram\n",
    prog);
}

CountOptions parse_count_args(int argc, char** argv)
{
  CountOptions opt;
  enum { NONE, BULK1, BULK2 } mode = NONE;

  for (int i = 2; i < argc; ++i) {
    if (strcmp(argv[i], "--bulk1") == 0) { mode = BULK1; continue; }
    if (strcmp(argv[i], "--bulk2") == 0) { mode = BULK2; continue; }
    if (strcmp(argv[i], "--only-bulk1") == 0) { opt.only_bulk1 = true; mode = NONE; continue; }
    if (strcmp(argv[i], "--only-bulk2") == 0) { opt.only_bulk2 = true; mode = NONE; continue; }
    if (strcmp(argv[i], "-o") == 0 && i+1 < argc) { opt.output_dir = argv[++i]; mode = NONE; continue; }
    if (strcmp(argv[i], "-k") == 0 && i+1 < argc) { opt.k = atoi(argv[++i]); mode = NONE; continue; }
    if (strcmp(argv[i], "-t") == 0 && i+1 < argc) { opt.threads = atoi(argv[++i]); mode = NONE; continue; }
    if (strcmp(argv[i], "-m") == 0 && i+1 < argc) { opt.mem_gb = atoi(argv[++i]); mode = NONE; continue; }
    if (strcmp(argv[i], "--ci") == 0 && i+1 < argc) { opt.ci = atoll(argv[++i]); mode = NONE; continue; }
    if (strcmp(argv[i], "--cs") == 0 && i+1 < argc) { opt.cs = atoll(argv[++i]); mode = NONE; continue; }

    if (mode == BULK1) opt.bulk1_files.push_back(argv[i]);
    else if (mode == BULK2) opt.bulk2_files.push_back(argv[i]);
  }

  if (opt.output_dir.empty()) {
    print_count_usage(argv[0]);
    exit(1);
  }
  if (!opt.only_bulk2 && opt.bulk1_files.empty()) {
    fprintf(stderr, "ERROR: --bulk1 files required\n");
    exit(1);
  }
  if (!opt.only_bulk1 && opt.bulk2_files.empty()) {
    fprintf(stderr, "ERROR: --bulk2 files required\n");
    exit(1);
  }
  return opt;
}

bool run_kmc_count(const std::vector<std::string>& input_files,
                   const std::string& output_db,
                   const std::string& tmp_dir,
                   uint32_t k, uint32_t threads, uint32_t mem_gb,
                   uint64_t ci, uint64_t cs)
{
  fs::create_directories(tmp_dir);

  KMC::Runner runner;

  KMC::Stage1Params s1;
  s1.SetInputFiles(input_files)
    .SetKmerLen(k)
    .SetNThreads(threads)
    .SetMaxRamGB(mem_gb)
    .SetTmpPath(tmp_dir)
    .SetInputFileType(KMC::InputFileType::FASTQ)
    .SetCanonicalKmers(true);

  auto r1 = runner.RunStage1(s1);
  fprintf(stderr, "  Stage1: %.1fs, %lu sequences\n", r1.time, (unsigned long)r1.nSeqences);

  KMC::Stage2Params s2;
  s2.SetCutoffMin(ci)
    .SetCounterMax(cs)
    .SetNThreads(threads)
    .SetMaxRamGB(mem_gb)
    .SetOutputFileName(output_db);

  auto r2 = runner.RunStage2(s2);
  fprintf(stderr, "  Stage2: %.1fs, %lu unique k-mers\n", r2.time, (unsigned long)r2.nUniqueKmers);

  fs::remove_all(tmp_dir);
  return true;
}

void generate_histogram(const std::string& db_path, const std::string& hist_path)
{
  CKMCFile db;
  if (!db.OpenForListing(db_path)) {
    fprintf(stderr, "ERROR: cannot open %s for histogram\n", db_path.c_str());
    return;
  }

  CKMCFileInfo info;
  db.Info(info);

  std::vector<uint64_t> hist(info.max_count + 1, 0);
  CKmerAPI kmer(info.kmer_length);
  uint32 count;
  while (db.ReadNextKmer(kmer, count)) {
    if (count <= info.max_count) hist[count]++;
  }
  db.Close();

  std::ofstream out(hist_path);
  for (uint64_t i = 1; i < hist.size(); ++i) {
    if (hist[i] > 0) out << i << "\t" << hist[i] << "\n";
  }
}

int cmd_count(int argc, char** argv)
{
  auto opt = parse_count_args(argc, argv);

  fs::create_directories(opt.output_dir);
  std::string bulk1_db = opt.output_dir + "/bulk1_db";
  std::string bulk2_db = opt.output_dir + "/bulk2_db";
  std::string bulk1_tmp = opt.output_dir + "/tmp_bulk1";
  std::string bulk2_tmp = opt.output_dir + "/tmp_bulk2";

  fprintf(stderr, "[kbsa count] k=%u, ci=%lu, threads=%u, mem=%uGB\n",
    opt.k, (unsigned long)opt.ci, opt.threads, opt.mem_gb);
  fprintf(stderr, "[kbsa count] Bulk1 files: %zu, Bulk2 files: %zu\n",
    opt.bulk1_files.size(), opt.bulk2_files.size());
  fprintf(stderr, "[kbsa count] Output: %s\n\n", opt.output_dir.c_str());

  auto t0 = std::chrono::steady_clock::now();

  if (!opt.only_bulk2) {
    fprintf(stderr, "[kbsa count] Counting bulk1 pool...\n");
    run_kmc_count(opt.bulk1_files, bulk1_db, bulk1_tmp,
                  opt.k, opt.threads, opt.mem_gb, opt.ci, opt.cs);
  }

  if (!opt.only_bulk1) {
    fprintf(stderr, "[kbsa count] Counting bulk2 pool...\n");
    run_kmc_count(opt.bulk2_files, bulk2_db, bulk2_tmp,
                  opt.k, opt.threads, opt.mem_gb, opt.ci, opt.cs);
  }

  fprintf(stderr, "\n[kbsa count] Generating histograms...\n");
  if (!opt.only_bulk2)
    generate_histogram(bulk1_db, opt.output_dir + "/bulk1_hist.txt");
  if (!opt.only_bulk1)
    generate_histogram(bulk2_db, opt.output_dir + "/bulk2_hist.txt");

  auto dt = std::chrono::duration_cast<std::chrono::seconds>(
    std::chrono::steady_clock::now() - t0).count();

  fprintf(stderr, "\n[kbsa count] Done in %lds.\n", (long)dt);
  fprintf(stderr, "  Bulk1 DB: %s\n", bulk1_db.c_str());
  fprintf(stderr, "  Bulk2 DB: %s\n", bulk2_db.c_str());
  fprintf(stderr, "  Histograms: %s/bulk1_hist.txt, bulk2_hist.txt\n", opt.output_dir.c_str());
  return 0;
}

Options parse_args(int argc, char** argv)
{
  Options opt;

  for (int i = 2; i < argc; ++i) {
    if (strcmp(argv[i], "--bulk1") == 0 && i+1 < argc)
      opt.bulk1_db = argv[++i];
    else if (strcmp(argv[i], "--bulk2") == 0 && i+1 < argc)
      opt.bulk2_db = argv[++i];
    else if (strcmp(argv[i], "--bulk1-hist") == 0 && i+1 < argc)
      opt.bulk1_hist = argv[++i];
    else if (strcmp(argv[i], "--bulk2-hist") == 0 && i+1 < argc)
      opt.bulk2_hist = argv[++i];
    else if ((strcmp(argv[i], "-o") == 0 || strcmp(argv[i], "--output") == 0) && i+1 < argc)
      opt.output = argv[++i];
    else if (strcmp(argv[i], "--kai-min") == 0 && i+1 < argc)
      opt.kai_min = atof(argv[++i]);
    else if (strcmp(argv[i], "--g-min") == 0 && i+1 < argc)
      opt.g_min = atof(argv[++i]);
    else if (strcmp(argv[i], "--error-rate") == 0 && i+1 < argc)
      opt.error_rate = atof(argv[++i]);
  }

  if (opt.bulk1_db.empty() || opt.bulk2_db.empty() ||
      opt.bulk1_hist.empty() || opt.bulk2_hist.empty() || opt.output.empty()) {
    print_usage(argv[0]);
    exit(1);
  }
  return opt;
}

int cmd_score(int argc, char** argv)
{
  auto opt = parse_args(argc, argv);

  fprintf(stderr, "[kbsa] Auto-calculating parameters from histograms...\n");
  auto params = auto_params(opt.bulk1_hist, opt.bulk2_hist,
                            opt.kai_min, opt.g_min, opt.error_rate);

  fprintf(stderr, "[kbsa] Parameters:\n");
  fprintf(stderr, "  scale_case_to_control = %.6f\n", params.bulk1_to_bulk2_scale);
  fprintf(stderr, "  min_depth = %lu\n", (unsigned long)params.min_depth);
  fprintf(stderr, "  max_depth = %lu\n", (unsigned long)params.max_depth);
  fprintf(stderr, "  kai_min = %.3f\n", params.kai_min);
  fprintf(stderr, "  g_min = %.3f\n", params.g_min);
  fprintf(stderr, "  error_rate = %.4f\n", params.error_rate);

  fprintf(stderr, "[kbsa] Opening KMC databases...\n");
  KmcMergeIterator merger(opt.bulk1_db, opt.bulk2_db);
  fprintf(stderr, "[kbsa] k = %u\n", merger.kmer_length());

  FILE* out = std::fopen(opt.output.c_str(), "wb");
  if (!out) {
    fprintf(stderr, "ERROR: cannot open output file: %s\n", opt.output.c_str());
    return 1;
  }
  static char io_buf[1 << 22];  // 4MB stdio buffer
  std::setvbuf(out, io_buf, _IOFBF, sizeof(io_buf));

  std::fputs("kmer\tsignificance\tkai_reg\tg_score\tz_score\tbulk2_raw\tbulk1_raw\tbulk2_adj\tbulk1_adj\n", out);

  auto t0 = std::chrono::steady_clock::now();
  uint64_t total = 0, passed = 0, bulk2_sig = 0, bulk1_sig = 0;
  char buf[512];

  MergedKmer mk;
  while (merger.next(mk)) {
    ++total;
    auto s = score_kmer(mk.bulk2_count, mk.bulk1_count,
                        params.bulk1_to_bulk2_scale,
                        params.min_depth, params.max_depth,
                        params.kai_min, params.g_min, params.error_rate);

    if (s.passed) {
      ++passed;
      if (s.sign == Significance::BULK2) ++bulk2_sig;
      else if (s.sign == Significance::BULK1) ++bulk1_sig;

      int n = snprintf(buf, sizeof(buf),
        "%s\t%s\t%.6f\t%.4f\t%+.4f\t%lu\t%lu\t%.4f\t%.4f\n",
        mk.kmer_str,
        significance_str(s.sign),
        s.kai_reg, s.g_score, s.z_score,
        (unsigned long)s.cnt_bulk2_raw, (unsigned long)s.cnt_bulk1_raw,
        s.cnt_bulk2_adj, s.cnt_bulk1_adj);
      std::fwrite(buf, 1, n, out);
    }

    if (total % 50000000 == 0) {
      auto dt = std::chrono::duration_cast<std::chrono::seconds>(
        std::chrono::steady_clock::now() - t0).count();
      fprintf(stderr, "[kbsa] %luM kmers processed, %luM passed (%lds)\n",
        (unsigned long)(total/1000000), (unsigned long)(passed/1000000), (long)dt);
    }
  }

  std::fclose(out);

  auto dt = std::chrono::duration_cast<std::chrono::seconds>(
    std::chrono::steady_clock::now() - t0).count();

  fprintf(stderr, "\n[kbsa] Done.\n");
  fprintf(stderr, "  Total kmers: %lu\n", (unsigned long)total);
  fprintf(stderr, "  Passed: %lu (%.2f%%)\n", (unsigned long)passed,
    total > 0 ? 100.0 * passed / total : 0.0);
  fprintf(stderr, "  BULK2-enriched: %lu\n", (unsigned long)bulk2_sig);
  fprintf(stderr, "  BULK1-enriched: %lu\n", (unsigned long)bulk1_sig);
  fprintf(stderr, "  Time: %lds\n", (long)dt);
  fprintf(stderr, "  Output: %s\n", opt.output.c_str());

  return 0;
}

static constexpr uint64_t kRepeatPeakMultiplier = 3;
static constexpr uint32_t kDefaultPermBlock = 100000;
static constexpr size_t kBedRowBufSize = 512;

struct AnchorOptions
{
  std::string reference;
  std::string bulk1_db;
  std::string bulk2_db;
  std::string bulk1_hist;
  std::string bulk2_hist;
  std::string output;
  uint32_t window_size {5000};
  uint32_t step_size {1000};
  double min_density {0.0};
  double min_consistency {0.0};
  double kai_min {0.0};
  double g_min {0.0};
  double error_rate {0.005};
  std::string target_chrom;
  bool per_position {false};
  bool peak_mode {false};
  uint32_t peak_window {1000000};
  std::string peak_stat {"sum"};  // sum or mean
  double peak_tau {2.0};  // excess-mass threshold: score = sum(max(0, |z|-tau))
  bool shared_only {false};  // require both bulks > 0 (legacy; default: allow one-sided)
  int threads {6};  // default: limit OMP threads (each thread opens own KMC RA, ~1.5GB index each)
  uint64_t override_peak1 {0};  // user-supplied peak (e.g., from GenomeScope2: round(2*kcov))
  uint64_t override_peak2 {0};
  bool assemble_orphans {false};
  uint32_t orphan_min_unitig {200};
  double orphan_tau {2.0};
  uint32_t n_perm {0};         // 0 = disable permutation FDR (default)
  uint32_t perm_block {kDefaultPermBlock};
};

void print_anchor_usage(const char* prog)
{
  fprintf(stderr,
    "kbsa anchor - Project k-mer differential scores onto reference positions\n\n"
    "Usage: %s anchor --ref <ref.fa> --bulk1 <db> --bulk2 <db> \\\n"
    "                       --bulk1-hist <hist.txt> --bulk2-hist <hist.txt> \\\n"
    "                       -o <output> [options]\n\n"
    "Default mode (window aggregation, BED output):\n"
    "  --window <int>       Sliding window size in bp (default: 5000)\n"
    "  --step <int>         Step size in bp (default: 1000)\n"
    "  --min-density <f>    Min hit fraction in window (default: 0.0)\n"
    "  --min-consistency <f> Min direction consistency (default: 0.0)\n\n"
    "Per-position mode (PATH A: tile + HMM):\n"
    "  --per-position       Output per-position TSV instead of windowed BED\n"
    "                       Columns: chrom  pos  bulk1_raw  bulk2_raw  z_score\n\n"
    "Peak mode (recommended for BSA QTL detection):\n"
    "  --peak               Output ranked Mb-window BED\n"
    "                       Default: include one-sided (one bulk=0) positions\n"
    "                       Per-Mb sum or mean |z_score|, sorted descending\n"
    "  --shared-only        Require both bulks > 0 (legacy strict filter)\n"
    "  --peak-window <int>  Window size in bp (default: 1000000)\n"
    "  --peak-stat <s>      Aggregate statistic: 'sum' (default) or 'mean'\n"
    "  --peak-tau <f>       Excess-mass threshold (default: 2.0)\n"
    "                       Set 0 for classic sum|z| (legacy mode)\n"
    "                       sum: sum(|z|) per window, length-biased toward larger SVs\n"
    "                       mean: mean(|z|) per window, density-normalized\n\n"
    "Common options:\n"
    "  --kai-min <f>        Min kai threshold (default: 0.0; emit all)\n"
    "  --g-min <f>          Min G-test threshold (default: 0.0; emit all)\n"
    "  --error-rate <f>     Error rate (default: 0.005)\n"
    "  --chrom <name>       Process only this chromosome\n",
    prog);
}

AnchorOptions parse_anchor_args(int argc, char** argv)
{
  AnchorOptions opt;
  for (int i = 2; i < argc; ++i) {
    if (strcmp(argv[i], "--ref") == 0 && i+1 < argc)
      opt.reference = argv[++i];
    else if ((strcmp(argv[i], "--bulk1") == 0 || strcmp(argv[i], "--case") == 0) && i+1 < argc)
      opt.bulk1_db = argv[++i];
    else if ((strcmp(argv[i], "--bulk2") == 0 || strcmp(argv[i], "--ctrl") == 0) && i+1 < argc)
      opt.bulk2_db = argv[++i];
    else if (strcmp(argv[i], "--bulk1-hist") == 0 && i+1 < argc)
      opt.bulk1_hist = argv[++i];
    else if (strcmp(argv[i], "--bulk2-hist") == 0 && i+1 < argc)
      opt.bulk2_hist = argv[++i];
    else if ((strcmp(argv[i], "-o") == 0 || strcmp(argv[i], "--output") == 0) && i+1 < argc)
      opt.output = argv[++i];
    else if (strcmp(argv[i], "--window") == 0 && i+1 < argc)
      opt.window_size = atoi(argv[++i]);
    else if (strcmp(argv[i], "--step") == 0 && i+1 < argc)
      opt.step_size = atoi(argv[++i]);
    else if (strcmp(argv[i], "--min-density") == 0 && i+1 < argc)
      opt.min_density = atof(argv[++i]);
    else if (strcmp(argv[i], "--min-consistency") == 0 && i+1 < argc)
      opt.min_consistency = atof(argv[++i]);
    else if (strcmp(argv[i], "--kai-min") == 0 && i+1 < argc)
      opt.kai_min = atof(argv[++i]);
    else if (strcmp(argv[i], "--g-min") == 0 && i+1 < argc)
      opt.g_min = atof(argv[++i]);
    else if (strcmp(argv[i], "--error-rate") == 0 && i+1 < argc)
      opt.error_rate = atof(argv[++i]);
    else if (strcmp(argv[i], "--chrom") == 0 && i+1 < argc)
      opt.target_chrom = argv[++i];
    else if (strcmp(argv[i], "--per-position") == 0)
      opt.per_position = true;
    else if (strcmp(argv[i], "--peak") == 0)
      opt.peak_mode = true;
    else if (strcmp(argv[i], "--peak-window") == 0 && i+1 < argc)
      opt.peak_window = atoi(argv[++i]);
    else if (strcmp(argv[i], "--peak-stat") == 0 && i+1 < argc)
      opt.peak_stat = argv[++i];
    else if (strcmp(argv[i], "--peak-tau") == 0 && i+1 < argc)
      opt.peak_tau = atof(argv[++i]);
    else if (strcmp(argv[i], "--shared-only") == 0)
      opt.shared_only = true;
    else if (strcmp(argv[i], "--assemble-orphans") == 0)
      opt.assemble_orphans = true;
    else if (strcmp(argv[i], "--orphan-min-unitig") == 0 && i+1 < argc)
      opt.orphan_min_unitig = atoi(argv[++i]);
    else if (strcmp(argv[i], "--threads") == 0 && i+1 < argc)
      opt.threads = std::max(1, atoi(argv[++i]));
    else if (strcmp(argv[i], "--peak1") == 0 && i+1 < argc)
      opt.override_peak1 = static_cast<uint64_t>(atoll(argv[++i]));
    else if (strcmp(argv[i], "--peak2") == 0 && i+1 < argc)
      opt.override_peak2 = static_cast<uint64_t>(atoll(argv[++i]));
    else if (strcmp(argv[i], "--perm") == 0 && i+1 < argc)
      opt.n_perm = static_cast<uint32_t>(atoi(argv[++i]));
    else if (strcmp(argv[i], "--perm-block") == 0 && i+1 < argc)
      opt.perm_block = static_cast<uint32_t>(atoi(argv[++i]));
  }

  if (opt.reference.empty() || opt.bulk1_db.empty() || opt.bulk2_db.empty() ||
      opt.bulk1_hist.empty() || opt.bulk2_hist.empty() || opt.output.empty()) {
    print_anchor_usage(argv[0]);
    exit(1);
  }
  return opt;
}

// --- Peak mode data structures ---
struct Block { double pos_ex = 0; double neg_ex = 0; uint32_t n = 0; };

struct Peak {
  std::string chrom;
  uint64_t mb;
  double pos_ex, neg_ex;
  uint64_t n;
  double p_emp = 1.0;
  double q_bh = 1.0;
};

struct ChromResult {
  std::vector<Peak> peaks;
  std::vector<Block> blocks;
  uint64_t n_hits = 0;
};

// Split z-score into directional excess-mass.
// score_kmer: z > 0 = BULK1-enriched (case), z < 0 = BULK2-enriched (ctrl).
// Returns {bulk1_excess, bulk2_excess} after subtracting tau.
static inline std::pair<double, double> directional_excess(double z, double tau)
{
  if (z > 0.0) {
    double e = z - tau;
    return {e > 0.0 ? e : 0.0, 0.0};
  }
  double e = -z - tau;
  return {0.0, e > 0.0 ? e : 0.0};
}

static void apply_permutation_fdr(
    std::vector<Peak>& all_peaks,
    const std::vector<ChromResult>& results,
    const std::vector<std::pair<std::string, std::string>>& chroms,
    uint32_t n_perm, uint32_t W, uint32_t B, int threads)
{
  fprintf(stderr, "[kbsa anchor] Permutation FDR: %u perms, block=%u bp\n", n_perm, B);
  auto t_perm0 = std::chrono::steady_clock::now();

  std::vector<double> obs_score(all_peaks.size());
  for (size_t i = 0; i < all_peaks.size(); ++i)
    obs_score[i] = std::max(all_peaks[i].pos_ex, all_peaks[i].neg_ex);

  std::vector<uint64_t> ge_count(all_peaks.size(), 0);

  std::vector<std::vector<size_t>> chrom_peaks(chroms.size());
  std::unordered_map<std::string, size_t> chrom_idx;
  for (size_t ci = 0; ci < chroms.size(); ++ci)
    chrom_idx[chroms[ci].first] = ci;
  for (size_t i = 0; i < all_peaks.size(); ++i) {
    auto it = chrom_idx.find(all_peaks[i].chrom);
    if (it != chrom_idx.end())
      chrom_peaks[it->second].push_back(i);
  }

  const uint32_t blocks_per_win = W / B;

  #pragma omp parallel num_threads(threads)
  {
    std::mt19937_64 rng(42 + omp_get_thread_num());
    std::vector<Block> shuffled;

    #pragma omp for schedule(dynamic)
    for (uint32_t perm = 0; perm < n_perm; ++perm) {
      for (size_t ci = 0; ci < chroms.size(); ++ci) {
        const auto& src_blocks = results[ci].blocks;
        if (src_blocks.empty()) continue;
        shuffled = src_blocks;
        std::shuffle(shuffled.begin(), shuffled.end(), rng);

        for (size_t pi : chrom_peaks[ci]) {
          uint64_t mb = all_peaks[pi].mb;
          size_t bi_start = mb * blocks_per_win;
          size_t bi_end = std::min(bi_start + blocks_per_win, shuffled.size());
          double null_pos = 0, null_neg = 0;
          for (size_t bi = bi_start; bi < bi_end; ++bi) {
            null_pos += shuffled[bi].pos_ex;
            null_neg += shuffled[bi].neg_ex;
          }
          double null_score = std::max(null_pos, null_neg);
          if (null_score >= obs_score[pi]) {
            #pragma omp atomic
            ge_count[pi] += 1;
          }
        }
      }
    }
  }

  for (size_t i = 0; i < all_peaks.size(); ++i)
    all_peaks[i].p_emp = (1.0 + ge_count[i]) / (1.0 + n_perm);

  std::vector<size_t> order(all_peaks.size());
  for (size_t i = 0; i < order.size(); ++i) order[i] = i;
  std::sort(order.begin(), order.end(),
    [&](size_t a, size_t b) { return all_peaks[a].p_emp < all_peaks[b].p_emp; });
  double m = (double)all_peaks.size();
  double prev_q = 1.0;
  for (ssize_t r = (ssize_t)order.size() - 1; r >= 0; --r) {
    size_t i = order[r];
    double q = all_peaks[i].p_emp * m / (r + 1);
    if (q > 1.0) q = 1.0;
    if (q < prev_q) prev_q = q;
    all_peaks[i].q_bh = prev_q;
  }

  auto dt_perm = std::chrono::duration_cast<std::chrono::seconds>(
    std::chrono::steady_clock::now() - t_perm0).count();
  fprintf(stderr, "[kbsa anchor] Permutation FDR done in %lds.\n", (long)dt_perm);
}

static int write_peak_bed(
    const std::string& path,
    const std::vector<Peak>& all_peaks,
    uint32_t W, bool use_mean, bool with_pvals)
{
  FILE* out = std::fopen(path.c_str(), "wb");
  if (!out) {
    fprintf(stderr, "ERROR: cannot open output: %s\n", path.c_str());
    return 1;
  }
  if (with_pvals)
    std::fputs("#chrom\tstart\tend\tn_kmers\tpos_excess\tneg_excess\tdir\tcoherence\tscore\tp_emp\tq_bh\n", out);
  else
    std::fputs("#chrom\tstart\tend\tn_kmers\tpos_excess\tneg_excess\tdir\tcoherence\tscore\n", out);

  char buf[kBedRowBufSize];
  for (const auto& p : all_peaks) {
    double score = std::max(p.pos_ex, p.neg_ex);
    double total_ex = p.pos_ex + p.neg_ex;
    double coherence = total_ex > 0.0 ? score / total_ex : 0.0;
    const char* dir = (p.pos_ex >= p.neg_ex) ? "BULK1" : "BULK2";
    double out_score = use_mean ? (p.n > 0 ? score / p.n : 0.0) : score;
    uint64_t start = p.mb * W;
    uint64_t end = start + W;
    int n;
    if (with_pvals) {
      n = snprintf(buf, sizeof(buf), "%s\t%lu\t%lu\t%lu\t%.4f\t%.4f\t%s\t%.4f\t%.4f\t%.4g\t%.4g\n",
        p.chrom.c_str(), (unsigned long)start, (unsigned long)end,
        (unsigned long)p.n, p.pos_ex, p.neg_ex, dir, coherence, out_score, p.p_emp, p.q_bh);
    } else {
      n = snprintf(buf, sizeof(buf), "%s\t%lu\t%lu\t%lu\t%.4f\t%.4f\t%s\t%.4f\t%.4f\n",
        p.chrom.c_str(), (unsigned long)start, (unsigned long)end,
        (unsigned long)p.n, p.pos_ex, p.neg_ex, dir, coherence, out_score);
    }
    std::fwrite(buf, 1, n, out);
  }
  std::fclose(out);
  return 0;
}

// Per-chromosome parallel scan: query each ref k-mer against both KMC DBs,
// accumulate directional excess into windows + blocks. Each thread opens its
// own KMC RA index (~1.5GB each).
static void run_peak_scan(
    const std::vector<std::pair<std::string, std::string>>& chroms,
    const std::string& bulk1_db,
    const std::string& bulk2_db,
    const Params& params,
    uint32_t k, uint32_t W, uint32_t B, double tau,
    uint64_t min_total, uint64_t max_total,
    uint32_t n_perm, int threads,
    std::vector<ChromResult>& results)
{
  #pragma omp parallel num_threads(threads)
  {
    KmcRandomAccess t_bulk1_ra, t_bulk2_ra;
    t_bulk1_ra.open(bulk1_db);
    t_bulk2_ra.open(bulk2_db);

    std::vector<char> t_fwd(k + 1, '\0');
    std::vector<char> t_rc(k + 1, '\0');
    std::vector<char> t_canon(k + 1, '\0');

    #pragma omp for schedule(dynamic)
    for (size_t ci = 0; ci < chroms.size(); ++ci) {
      const auto& [cname, cseq] = chroms[ci];
      const uint64_t n_pos = cseq.size() - k + 1;
      size_t n_win = cseq.size() / W + 1;
      size_t n_blk = (n_perm > 0) ? (cseq.size() / B + 1) : 0;
      std::vector<double> win_pos(n_win, 0.0);
      std::vector<double> win_neg(n_win, 0.0);
      std::vector<uint64_t> win_cnt(n_win, 0);
      std::vector<Block> blocks(n_blk);
      uint64_t hits = 0;

      for (uint64_t pos = 0; pos < n_pos; ++pos) {
        const char* start = cseq.data() + pos;
        if (has_ambiguous(start, k)) continue;
        memcpy(t_fwd.data(), start, k);
        canonicalize(t_fwd.data(), t_canon.data(), t_rc.data(), k);

        uint64_t bulk1_cnt = t_bulk1_ra.query(t_canon.data());
        uint64_t bulk2_cnt = t_bulk2_ra.query(t_canon.data());

        uint64_t max_cnt = std::max(bulk1_cnt, bulk2_cnt);
        uint64_t total = bulk1_cnt + bulk2_cnt;
        if (max_cnt < min_total || total > max_total) continue;

        auto s = score_kmer(bulk2_cnt, bulk1_cnt,
                            params.bulk1_to_bulk2_scale,
                            params.min_depth, params.max_depth,
                            params.kai_min, params.g_min, params.error_rate);
        if (!s.passed) continue;
        ++hits;
        size_t mb = pos / W;
        auto [pos_e, neg_e] = directional_excess(s.z_score, tau);
        win_pos[mb] += pos_e;
        win_neg[mb] += neg_e;
        win_cnt[mb] += 1;
        if (n_perm > 0) {
          size_t bi = pos / B;
          blocks[bi].pos_ex += pos_e;
          blocks[bi].neg_ex += neg_e;
          blocks[bi].n += 1;
        }
      }

      auto& cr = results[ci];
      cr.n_hits = hits;
      for (size_t mb = 0; mb < n_win; ++mb) {
        if (win_cnt[mb] > 0)
          cr.peaks.push_back({cname, mb, win_pos[mb], win_neg[mb], win_cnt[mb], 1.0, 1.0});
      }
      cr.blocks = std::move(blocks);
    }

    t_bulk1_ra.close();
    t_bulk2_ra.close();
  }
}

int cmd_anchor(int argc, char** argv)
{
  auto opt = parse_anchor_args(argc, argv);

  fprintf(stderr, "[kbsa anchor] Auto-calculating parameters...\n");
  auto params = auto_params(opt.bulk1_hist, opt.bulk2_hist,
                            opt.kai_min, opt.g_min, opt.error_rate);

  fprintf(stderr, "[kbsa anchor] Parameters:\n");
  fprintf(stderr, "  scale = %.6f, min_depth = %lu, max_depth = %lu\n",
    params.bulk1_to_bulk2_scale,
    (unsigned long)params.min_depth, (unsigned long)params.max_depth);
  fprintf(stderr, "  kai_min = %.3f, g_min = %.3f\n", params.kai_min, params.g_min);
  fprintf(stderr, "  window = %u, step = %u\n", opt.window_size, opt.step_size);
  fprintf(stderr, "  min_density = %.3f, min_consistency = %.2f\n",
    opt.min_density, opt.min_consistency);

  fprintf(stderr, "[kbsa anchor] Opening KMC databases (random access)...\n");
  KmcRandomAccess bulk1_ra, bulk2_ra;
  if (!bulk1_ra.open(opt.bulk1_db))
    { fprintf(stderr, "ERROR: cannot open bulk1 db: %s\n", opt.bulk1_db.c_str()); return 1; }
  if (!bulk2_ra.open(opt.bulk2_db))
    { fprintf(stderr, "ERROR: cannot open bulk2 db: %s\n", opt.bulk2_db.c_str()); return 1; }

  const uint32_t k = bulk1_ra.kmer_length();
  fprintf(stderr, "[kbsa anchor] k = %u\n", k);

  // For peak mode: pre-read all chromosomes, then parallel process
  if (opt.peak_mode) {
    bulk1_ra.close();
    bulk2_ra.close();

    // Read all chromosomes
    FastaReader fasta(opt.reference);
    std::string chrom_name, chrom_seq;
    std::vector<std::pair<std::string, std::string>> chroms;
    while (fasta.next_chromosome(chrom_name, chrom_seq)) {
      if (!opt.target_chrom.empty() && chrom_name != opt.target_chrom) continue;
      if (chrom_seq.size() < k) continue;
      chroms.emplace_back(std::move(chrom_name), std::move(chrom_seq));
    }
    fprintf(stderr, "[kbsa anchor] Loaded %zu chromosomes for parallel peak scan\n", chroms.size());
    fprintf(stderr, "[kbsa anchor] Using %d threads (each opens own KMC RA, ~1.5GB index/thread)\n", opt.threads);
    if (opt.peak_tau > 0.0)
      fprintf(stderr, "[kbsa anchor] Excess-mass mode: tau=%.2f (score = sum(max(0, |z|-tau)))\n", opt.peak_tau);

    // Error/repeat filter derived from histogram (no empirical parameters)
    auto hist1_pk = load_histogram(opt.bulk1_hist);
    auto hist2_pk = load_histogram(opt.bulk2_hist);
    uint64_t valley1 = find_valley_depth(hist1_pk);
    uint64_t valley2 = find_valley_depth(hist2_pk);
    uint64_t peak1_v = opt.override_peak1 ? opt.override_peak1 : find_peak_depth(hist1_pk);
    uint64_t peak2_v = opt.override_peak2 ? opt.override_peak2 : find_peak_depth(hist2_pk);
    uint64_t min_total = std::max(valley1, valley2);
    uint64_t max_total = std::max(peak1_v, peak2_v) * kRepeatPeakMultiplier;
    fprintf(stderr, "[kbsa anchor] Peak1=%lu%s, Peak2=%lu%s, valley1=%lu, valley2=%lu\n",
            peak1_v, opt.override_peak1 ? "(override)" : "(heuristic)",
            peak2_v, opt.override_peak2 ? "(override)" : "(heuristic)",
            valley1, valley2);
    fprintf(stderr, "[kbsa anchor] Error/repeat filter: min_total=%lu, max_total=%lu\n",
            min_total, max_total);

    auto t0 = std::chrono::steady_clock::now();
    const uint32_t W = opt.peak_window;
    bool use_mean = (opt.peak_stat == "mean");
    const double tau = opt.peak_tau;

    std::vector<ChromResult> results(chroms.size());
    const uint32_t B = opt.perm_block;

    run_peak_scan(chroms, opt.bulk1_db, opt.bulk2_db, params,
                  k, W, B, tau, min_total, max_total,
                  opt.n_perm, opt.threads, results);

    // Merge peaks from per-chromosome results
    std::vector<Peak> all_peaks;
    uint64_t total_hits = 0;
    for (size_t ci = 0; ci < chroms.size(); ++ci) {
      total_hits += results[ci].n_hits;
      for (auto& p : results[ci].peaks)
        all_peaks.push_back(std::move(p));
      fprintf(stderr, "  %s: %lu hits\n",
        chroms[ci].first.c_str(), (unsigned long)results[ci].n_hits);
    }

    // ---- Optional: Block-permutation FDR ----
    if (opt.n_perm > 0)
      apply_permutation_fdr(all_peaks, results, chroms, opt.n_perm, W, B, opt.threads);

    // Sort: score = max(pos, neg). Coherence = score / (pos + neg).
    std::sort(all_peaks.begin(), all_peaks.end(),
      [use_mean](const Peak& a, const Peak& b) {
        double sa = std::max(a.pos_ex, a.neg_ex);
        double sb = std::max(b.pos_ex, b.neg_ex);
        if (use_mean) {
          sa /= std::max((uint64_t)1, a.n);
          sb /= std::max((uint64_t)1, b.n);
        }
        return sa > sb;
      });

    if (write_peak_bed(opt.output, all_peaks, W, use_mean, opt.n_perm > 0) != 0)
      return 1;

    auto dt = std::chrono::duration_cast<std::chrono::seconds>(
      std::chrono::steady_clock::now() - t0).count();
    fprintf(stderr, "\n[kbsa anchor] Peak mode done (parallel).\n");
    fprintf(stderr, "  Chromosomes: %zu\n", chroms.size());
    fprintf(stderr, "  Total hits: %lu\n", (unsigned long)total_hits);
    fprintf(stderr, "  Windows ranked: %zu (by %s)\n", all_peaks.size(), opt.peak_stat.c_str());
    fprintf(stderr, "  Time: %lds\n", (long)dt);
    fprintf(stderr, "  Output: %s\n", opt.output.c_str());

    // --- Orphan assembly ---
    if (opt.assemble_orphans) {
      fprintf(stderr, "\n[kbsa anchor] Assembling orphan k-mers (--assemble-orphans)...\n");

      Params unitig_params;
      unitig_params.bulk1_to_bulk2_scale = params.bulk1_to_bulk2_scale;
      unitig_params.error_rate = params.error_rate;

      auto diff_kmers = extract_differential_kmers(
          opt.bulk1_db, opt.bulk2_db, opt.bulk1_hist, opt.bulk2_hist,
          unitig_params, 0, 0);
      fprintf(stderr, "[kbsa anchor] Differential k-mers: %zu\n", diff_kmers.size());

      // Walk reference and mark k-mers that appear on it
      size_t n_anchored = 0;
      for (const auto& [cname, cseq] : chroms) {
        for (size_t pos = 0; pos + k <= cseq.size(); ++pos) {
          const char* start = cseq.data() + pos;
          if (has_ambiguous(start, k)) continue;
          uint64_t can = string_kmer_to_canonical(start, k);
          if (diff_kmers.erase(can)) ++n_anchored;
        }
      }
      fprintf(stderr, "[kbsa anchor] Anchored (removed): %zu, orphans remaining: %zu\n",
              n_anchored, diff_kmers.size());

      if (!diff_kmers.empty()) {
        auto orphan_unitigs = extract_unitigs(diff_kmers, k, opt.orphan_min_unitig);
        fprintf(stderr, "[kbsa anchor] Orphan unitigs assembled: %zu\n", orphan_unitigs.size());

        auto orphan_scores = score_and_rank_unitigs(
            orphan_unitigs, k, diff_kmers, unitig_params,
            static_cast<float>(opt.orphan_tau));

        // Write orphan FASTA
        std::string prefix = opt.output;
        auto dot = prefix.rfind('.');
        if (dot != std::string::npos) prefix = prefix.substr(0, dot);

        std::string ofa = prefix + "_orphan_unitigs.fa";
        std::ofstream ofa_out(ofa);
        for (const auto& s : orphan_scores) {
          ofa_out << ">" << s.id << " len=" << s.length
                  << " rank_score=" << s.rank_score << "\n"
                  << s.sequence << "\n";
        }
        ofa_out.close();

        std::string otsv = prefix + "_orphan_unitigs.tsv";
        std::ofstream otsv_out(otsv);
        otsv_out << "unitig_id\tlength\tn_kmers\tdominant_dir\tcoherence\tmean_z\t"
                    "excess_per_kb\tsum_excess_mass\tsum_bulk1\tsum_bulk2\n";
        for (const auto& s : orphan_scores) {
          const char* dir = (s.dominant_dir > 0) ? "BULK1" : "BULK2";
          char buf[512];
          int n = snprintf(buf, sizeof(buf),
            "%s\t%u\t%u\t%s\t%.4f\t%.4f\t%.4f\t%.4f\t%lu\t%lu\n",
            s.id.c_str(), s.length, s.n_kmers, dir,
            s.coherence, s.mean_z, s.excess_per_kb, s.sum_excess_mass,
            s.sum_bulk1, s.sum_bulk2);
          otsv_out.write(buf, n);
        }
        otsv_out.close();

        fprintf(stderr, "[kbsa anchor] Orphan output: %s (%zu unitigs)\n",
                ofa.c_str(), orphan_scores.size());
        fprintf(stderr, "[kbsa anchor] Orphan output: %s\n", otsv.c_str());
      } else {
        fprintf(stderr, "[kbsa anchor] No orphan k-mers — all differential k-mers are anchored.\n");
      }
    }

    return 0;
  }

  // --- Non-peak modes (per-position / legacy window) below ---

  std::ofstream out(opt.output);
  if (!out.good())
    { fprintf(stderr, "ERROR: cannot open output: %s\n", opt.output.c_str()); return 1; }

  if (opt.peak_mode)
    out << "#chrom\tstart\tend\tn_kmers\tsum_abs_z\tmean_abs_z\tpeak_score\n";
  else if (opt.per_position)
    out << "#chrom\tpos\tbulk1_raw\tbulk2_raw\tz_score\n";
  else
    out << "#chrom\tstart\tend\thits\twindow_kmers\tdensity\tconsistency"
        << "\tmean_kai_dev\tmax_g\n";

  // Per-chromosome peak data (only used in --peak mode):
  //   key = (chrom_name, mb_index), value = (sum_abs_z, count)
  std::vector<std::tuple<std::string, uint64_t, double, uint64_t>> all_peaks;

  auto t0 = std::chrono::steady_clock::now();
  uint64_t total_intervals = 0;
  uint64_t total_chroms = 0;

  FastaReader fasta(opt.reference);
  std::string chrom_name, chrom_seq;

  std::vector<char> fwd_buf(k + 1, '\0');
  std::vector<char> rc_buf(k + 1, '\0');
  std::vector<char> canon_buf(k + 1, '\0');

  while (fasta.next_chromosome(chrom_name, chrom_seq)) {
    if (!opt.target_chrom.empty() && chrom_name != opt.target_chrom)
      continue;

    if (chrom_seq.size() < k) continue;
    ++total_chroms;

    const uint64_t n_positions = chrom_seq.size() - k + 1;
    fprintf(stderr, "[kbsa anchor] %s: %lu bp, %lu k-mer positions\n",
      chrom_name.c_str(), (unsigned long)chrom_seq.size(), (unsigned long)n_positions);

    if (opt.peak_mode || opt.per_position) {
      // Per-position scan: for peak mode, aggregate into Mb windows on the fly.
      // one-sided filter: skip only if both bulks are zero
      uint64_t n_hits = 0;
      char buf[256];

      // Peak mode: per-Mb window accumulators for THIS chromosome
      std::vector<double> win_sum_abs_z;
      std::vector<uint64_t> win_count;
      const uint32_t W = opt.peak_window;
      if (opt.peak_mode) {
        size_t n_win = chrom_seq.size() / W + 1;
        win_sum_abs_z.assign(n_win, 0.0);
        win_count.assign(n_win, 0);
      }

      for (uint64_t pos = 0; pos < n_positions; ++pos) {
        const char* start = chrom_seq.data() + pos;
        if (has_ambiguous(start, k)) continue;

        memcpy(fwd_buf.data(), start, k);
        fwd_buf[k] = '\0';
        canonicalize(fwd_buf.data(), canon_buf.data(), rc_buf.data(), k);

        uint64_t bulk1_cnt = bulk1_ra.query(canon_buf.data());
        uint64_t bulk2_cnt = bulk2_ra.query(canon_buf.data());

        // shared-only filter for peak mode (BSA proper signal)
        // per-position mode: emit any non-zero
        if (opt.peak_mode) {
          if (opt.shared_only) {
            if (bulk1_cnt == 0 || bulk2_cnt == 0) continue;
          } else {
            if (bulk1_cnt == 0 && bulk2_cnt == 0) continue;
          }
        } else {
          if (bulk1_cnt == 0 && bulk2_cnt == 0) continue;
        }

        auto s = score_kmer(bulk2_cnt, bulk1_cnt,
                            params.bulk1_to_bulk2_scale,
                            params.min_depth, params.max_depth,
                            params.kai_min, params.g_min, params.error_rate);

        if (!s.passed) continue;
        ++n_hits;

        if (opt.peak_mode) {
          size_t mb = pos / W;
          if (mb < win_sum_abs_z.size()) {
            double excess = std::abs(s.z_score) - opt.peak_tau;
            if (excess > 0.0)
              win_sum_abs_z[mb] += excess;
            win_count[mb] += 1;
          }
        } else {
          int n = snprintf(buf, sizeof(buf), "%s\t%lu\t%lu\t%lu\t%+.4f\n",
            chrom_name.c_str(), (unsigned long)pos,
            (unsigned long)bulk1_cnt, (unsigned long)bulk2_cnt, s.z_score);
          out.write(buf, n);
        }

        if (pos % 5000000 == 0 && pos > 0) {
          auto dt = std::chrono::duration_cast<std::chrono::seconds>(
            std::chrono::steady_clock::now() - t0).count();
          fprintf(stderr, "  %luM positions, %lu hits (%lds)\n",
            (unsigned long)(pos/1000000), (unsigned long)n_hits, (long)dt);
        }
      }

      // Stash peak windows for global ranking
      if (opt.peak_mode) {
        for (size_t mb = 0; mb < win_sum_abs_z.size(); ++mb) {
          if (win_count[mb] > 0) {
            all_peaks.emplace_back(chrom_name, mb, win_sum_abs_z[mb], win_count[mb]);
          }
        }
      }

      fprintf(stderr, "  %lu hits from %lu positions (%.2f%%)\n",
        (unsigned long)n_hits, (unsigned long)n_positions,
        n_positions > 0 ? 100.0 * n_hits / n_positions : 0.0);
      total_intervals += n_hits;
      continue;  // skip legacy window aggregation
    }

    // Window mode (legacy)
    std::vector<AnchorHit> hits;
    hits.reserve(n_positions / 10);

    for (uint64_t pos = 0; pos < n_positions; ++pos) {
      const char* start = chrom_seq.data() + pos;
      if (has_ambiguous(start, k)) continue;

      memcpy(fwd_buf.data(), start, k);
      fwd_buf[k] = '\0';
      canonicalize(fwd_buf.data(), canon_buf.data(), rc_buf.data(), k);

      uint64_t bulk1_cnt = bulk1_ra.query(canon_buf.data());
      uint64_t bulk2_cnt = bulk2_ra.query(canon_buf.data());

      auto s = score_kmer(bulk2_cnt, bulk1_cnt,
                          params.bulk1_to_bulk2_scale,
                          params.min_depth, params.max_depth,
                          params.kai_min, params.g_min, params.error_rate);

      if (s.passed) {
        hits.push_back({pos, s.kai_reg, s.g_score, s.sign});
      }
    }

    fprintf(stderr, "  %lu hits from %lu positions (%.2f%%)\n",
      (unsigned long)hits.size(), (unsigned long)n_positions,
      n_positions > 0 ? 100.0 * hits.size() / n_positions : 0.0);

    if (hits.empty()) continue;

    for (uint64_t win_start = 0;
         win_start + opt.window_size <= chrom_seq.size();
         win_start += opt.step_size)
    {
      uint64_t win_end = win_start + opt.window_size;
      uint32_t window_kmers = opt.window_size - k + 1;

      auto it_lo = std::lower_bound(hits.begin(), hits.end(), win_start,
        [](const AnchorHit& h, uint64_t v) { return h.position < v; });
      auto it_hi = std::lower_bound(hits.begin(), hits.end(), win_end,
        [](const AnchorHit& h, uint64_t v) { return h.position < v; });

      uint32_t hit_count = static_cast<uint32_t>(it_hi - it_lo);
      if (hit_count == 0) continue;

      double density = static_cast<double>(hit_count) / window_kmers;
      if (density < opt.min_density) continue;

      uint32_t bulk2_dir = 0, bulk1_dir = 0;
      double kai_dev_sum = 0.0;
      double max_g = 0.0;
      for (auto it = it_lo; it != it_hi; ++it) {
        if (it->direction == Significance::BULK2) ++bulk2_dir;
        else ++bulk1_dir;
        kai_dev_sum += std::abs(it->kai_reg - 0.5);
        if (it->g_score > max_g) max_g = it->g_score;
      }

      double consistency = static_cast<double>(std::max(bulk2_dir, bulk1_dir)) / hit_count;
      if (consistency < opt.min_consistency) continue;

      double mean_kai_dev = kai_dev_sum / hit_count;

      char buf[512];
      int n = snprintf(buf, sizeof(buf),
        "%s\t%lu\t%lu\t%u\t%u\t%.4f\t%.3f\t%.4f\t%.2f\n",
        chrom_name.c_str(),
        (unsigned long)win_start, (unsigned long)win_end,
        hit_count, window_kmers, density, consistency,
        mean_kai_dev, max_g);
      out.write(buf, n);
      ++total_intervals;
    }
  }

  // Peak mode: sort all windows globally and output ranked BED
  if (opt.peak_mode && !all_peaks.empty()) {
    bool use_mean = (opt.peak_stat == "mean");
    // Sort by chosen statistic descending
    std::sort(all_peaks.begin(), all_peaks.end(),
      [use_mean](const auto& a, const auto& b) {
        double sa = use_mean ? std::get<2>(a) / std::max((uint64_t)1, std::get<3>(a))
                             : std::get<2>(a);
        double sb = use_mean ? std::get<2>(b) / std::max((uint64_t)1, std::get<3>(b))
                             : std::get<2>(b);
        return sa > sb;
      });

    char buf[512];
    const uint32_t W = opt.peak_window;
    for (const auto& [chrom, mb, sum_abs, cnt] : all_peaks) {
      double mean_abs = cnt > 0 ? sum_abs / cnt : 0.0;
      double score = use_mean ? mean_abs : sum_abs;
      uint64_t start = mb * W;
      uint64_t end = start + W;
      int n = snprintf(buf, sizeof(buf), "%s\t%lu\t%lu\t%lu\t%.4f\t%.6f\t%.4f\n",
        chrom.c_str(), (unsigned long)start, (unsigned long)end,
        (unsigned long)cnt, sum_abs, mean_abs, score);
      out.write(buf, n);
    }
    fprintf(stderr, "[kbsa anchor] Peak mode: %zu windows ranked by %s\n",
      all_peaks.size(), opt.peak_stat.c_str());
  }

  bulk1_ra.close();
  bulk2_ra.close();

  auto dt = std::chrono::duration_cast<std::chrono::seconds>(
    std::chrono::steady_clock::now() - t0).count();

  fprintf(stderr, "\n[kbsa anchor] Done.\n");
  fprintf(stderr, "  Chromosomes: %lu\n", (unsigned long)total_chroms);
  fprintf(stderr, "  Candidate intervals: %lu\n", (unsigned long)total_intervals);
  fprintf(stderr, "  Time: %lds\n", (long)dt);
  fprintf(stderr, "  Output: %s\n", opt.output.c_str());
  return 0;
}

struct RankOptions
{
  std::string score_tsv;
  std::string unitig_fa;
  std::string output;
  double min_g {0.0};
  uint32_t min_kmers_scored {1};
  bool include_seq {false};
};

void print_rank_usage(const char* prog)
{
  fprintf(stderr,
    "kbsa rank - aggregate per-k-mer scores onto BCALM2 unitigs\n\n"
    "Usage: %s rank --score <scored.tsv> --unitigs <unitigs.fa> -o <ranked.tsv> [opts]\n\n"
    "Options:\n"
    "  --min-g <float>    Pre-filter k-mers below g_score (default: 0.0)\n"
    "  --min-kmers <int>  Skip unitigs with fewer scored k-mers (default: 1)\n"
    "  --emit-seq         Include unitig sequence column\n\n"
    "Output ranked by sum_abs_z desc.\n", prog);
}

int cmd_rank(int argc, char** argv)
{
  RankOptions opt;
  for (int i = 2; i < argc; ++i) {
    if (strcmp(argv[i], "--score") == 0 && i+1 < argc) opt.score_tsv = argv[++i];
    else if (strcmp(argv[i], "--unitigs") == 0 && i+1 < argc) opt.unitig_fa = argv[++i];
    else if (strcmp(argv[i], "-o") == 0 && i+1 < argc) opt.output = argv[++i];
    else if (strcmp(argv[i], "--min-g") == 0 && i+1 < argc) opt.min_g = atof(argv[++i]);
    else if (strcmp(argv[i], "--min-kmers") == 0 && i+1 < argc) opt.min_kmers_scored = atoi(argv[++i]);
    else if (strcmp(argv[i], "--emit-seq") == 0) opt.include_seq = true;
    else if (strcmp(argv[i], "-h") == 0 || strcmp(argv[i], "--help") == 0) {
      print_rank_usage(argv[0]); return 0;
    } else { fprintf(stderr, "Unknown arg: %s\n", argv[i]); return 1; }
  }
  if (opt.score_tsv.empty() || opt.unitig_fa.empty() || opt.output.empty()) {
    print_rank_usage(argv[0]); return 1;
  }

  fprintf(stderr, "[rank] loading score table from %s ...\n", opt.score_tsv.c_str());
  std::unordered_map<uint64_t, KmerEntry> tbl;
  size_t n_loaded = load_score_table(opt.score_tsv, opt.min_g, tbl);
  if (n_loaded == 0) return 1;

  fprintf(stderr, "[rank] aggregating unitigs from %s ...\n", opt.unitig_fa.c_str());
  std::ifstream fa(opt.unitig_fa);
  if (!fa.good()) { fprintf(stderr, "ERROR: open %s\n", opt.unitig_fa.c_str()); return 1; }

  std::vector<UnitigStats> rows;
  std::string line, header, seq;
  auto flush = [&]() {
    if (header.empty() || seq.empty()) return;
    auto u = aggregate_unitig(header, seq, tbl);
    if (u.n_kmers_scored >= opt.min_kmers_scored) rows.push_back(std::move(u));
  };
  while (std::getline(fa, line)) {
    if (line.empty()) continue;
    if (line[0] == '>') {
      flush();
      size_t sp = line.find(' ');
      header = (sp == std::string::npos) ? line.substr(1) : line.substr(1, sp - 1);
      seq.clear();
    } else {
      seq.append(line);
    }
  }
  flush();

  fprintf(stderr, "[rank] %zu unitigs aggregated; sorting by sum_abs_z ...\n", rows.size());
  std::sort(rows.begin(), rows.end(),
    [](const UnitigStats& a, const UnitigStats& b) { return a.sum_abs_z > b.sum_abs_z; });

  std::ofstream out(opt.output);
  if (!out.good()) { fprintf(stderr, "ERROR: open %s\n", opt.output.c_str()); return 1; }
  out << "rank\tunitig_id\tlength\tn_kmers\tn_scored\tn_bulk1\tn_bulk2\t"
         "sum_abs_z\tmedian_abs_z\tmax_abs_z\tsigned_sum_z\tdominant_dir";
  if (opt.include_seq) out << "\tsequence";
  out << "\n";

  char buf[1024];
  for (size_t i = 0; i < rows.size(); ++i) {
    const auto& u = rows[i];
    const char* dir = (u.n_bulk2 > u.n_bulk1) ? "BULK2" :
                      (u.n_bulk1 > u.n_bulk2) ? "BULK1" : "MIXED";
    int n = snprintf(buf, sizeof(buf),
      "%zu\t%s\t%u\t%u\t%u\t%u\t%u\t%.4f\t%.4f\t%.4f\t%+.4f\t%s",
      i + 1, u.id.c_str(), u.length, u.n_kmers_total, u.n_kmers_scored,
      u.n_bulk1, u.n_bulk2, u.sum_abs_z, u.median_abs_z, u.max_abs_z,
      u.sum_signed_z, dir);
    out.write(buf, n);
    if (opt.include_seq) { out.put('\t'); out.write(u.sequence.data(), u.sequence.size()); }
    out.put('\n');
  }
  fprintf(stderr, "[rank] wrote %zu ranked unitigs to %s\n", rows.size(), opt.output.c_str());
  return 0;
}

// ===================== unitig subcommand =====================

struct UnitigOptions
{
  std::string bulk1_db;
  std::string bulk2_db;
  std::string bulk1_hist;
  std::string bulk2_hist;
  std::string output;
  std::string map_ref;
  std::string parent1_db;
  std::string parent2_db;
  uint32_t min_count {0};
  uint32_t max_opp {0};
  uint32_t min_unitig {200};
  double tau {2.0};
  double error_rate {0.005};
  bool extend {false};
};

void print_unitig_usage(const char* prog)
{
  fprintf(stderr,
    "kbsa unitig - Reference-free BSA unitig assembly\n\n"
    "Usage: %s unitig --bulk1 <db> --bulk2 <db> \\\n"
    "                       -o <output_prefix> [options]\n\n"
    "Options:\n"
    "  --bulk1-hist <hist>  Bulk1 histogram (optional; computed from DB if omitted)\n"
    "  --bulk2-hist <hist>  Bulk2 histogram (optional; computed from DB if omitted)\n"
    "  --min-count <int>    Min enriched-bulk count (default: auto from histogram)\n"
    "  --max-opp <int>      Max opposite-bulk count (default: auto from histogram)\n"
    "  --min-unitig <int>   Min unitig length in bp (default: 200)\n"
    "  --tau <float>        Excess-mass z threshold (default: 2.0)\n"
    "  --error-rate <float> Error rate for epsilon (default: 0.005)\n"
    "  --map-ref <ref.fa>   Optional: map unitigs to reference, output BED\n"
    "  --extend             Two-phase extension: extend unitigs using full KMC DBs\n\n"
    "Output:\n"
    "  <prefix>_unitigs.fa  — FASTA sequences\n"
    "  <prefix>_unitigs.tsv — Per-unitig score table\n"
    "  <prefix>_unitigs.bed — BED6 mapping (only with --map-ref)\n",
    prog);
}

UnitigOptions parse_unitig_args(int argc, char** argv)
{
  UnitigOptions opt;
  for (int i = 2; i < argc; ++i) {
    if (strcmp(argv[i], "--bulk1") == 0 && i+1 < argc) opt.bulk1_db = argv[++i];
    else if (strcmp(argv[i], "--bulk2") == 0 && i+1 < argc) opt.bulk2_db = argv[++i];
    else if (strcmp(argv[i], "--bulk1-hist") == 0 && i+1 < argc) opt.bulk1_hist = argv[++i];
    else if (strcmp(argv[i], "--bulk2-hist") == 0 && i+1 < argc) opt.bulk2_hist = argv[++i];
    else if ((strcmp(argv[i], "-o") == 0 || strcmp(argv[i], "--output") == 0) && i+1 < argc)
      opt.output = argv[++i];
    else if (strcmp(argv[i], "--min-count") == 0 && i+1 < argc) opt.min_count = std::atoi(argv[++i]);
    else if (strcmp(argv[i], "--max-opp") == 0 && i+1 < argc) opt.max_opp = std::atoi(argv[++i]);
    else if (strcmp(argv[i], "--min-unitig") == 0 && i+1 < argc) opt.min_unitig = std::atoi(argv[++i]);
    else if (strcmp(argv[i], "--tau") == 0 && i+1 < argc) opt.tau = std::atof(argv[++i]);
    else if (strcmp(argv[i], "--error-rate") == 0 && i+1 < argc) opt.error_rate = std::atof(argv[++i]);
    else if (strcmp(argv[i], "--map-ref") == 0 && i+1 < argc) opt.map_ref = argv[++i];
    else if (strcmp(argv[i], "--parent1") == 0 && i+1 < argc) opt.parent1_db = argv[++i];
    else if (strcmp(argv[i], "--parent2") == 0 && i+1 < argc) opt.parent2_db = argv[++i];
    else if (strcmp(argv[i], "--extend") == 0) opt.extend = true;
    else {
      fprintf(stderr, "Unknown option: %s\n", argv[i]);
      print_unitig_usage(argv[0]);
      exit(1);
    }
  }
  return opt;
}

int cmd_unitig(int argc, char** argv)
{
  if (argc < 3) { print_unitig_usage(argv[0]); return 1; }
  auto opt = parse_unitig_args(argc, argv);

  if (opt.bulk1_db.empty() || opt.bulk2_db.empty() || opt.output.empty()) {
    fprintf(stderr, "[unitig] Error: --bulk1, --bulk2, -o required\n");
    print_unitig_usage(argv[0]);
    return 1;
  }

  Params params;
  params.bulk1_to_bulk2_scale = 1.0;
  params.error_rate = opt.error_rate;

  auto hist1 = opt.bulk1_hist.empty()
    ? compute_histogram_from_db(opt.bulk1_db)
    : load_histogram(opt.bulk1_hist);
  auto hist2 = opt.bulk2_hist.empty()
    ? compute_histogram_from_db(opt.bulk2_db)
    : load_histogram(opt.bulk2_hist);
  uint64_t peak1 = find_peak_depth(hist1);
  uint64_t peak2 = find_peak_depth(hist2);
  params.bulk1_to_bulk2_scale = static_cast<double>(peak2) / std::max<uint64_t>(peak1, 1);

  fprintf(stderr, "[unitig] bulk1 peak=%lu, bulk2 peak=%lu, scale=%.3f\n",
          peak1, peak2, params.bulk1_to_bulk2_scale);

  // --- BCALM2 pipeline: stream diff k-mers → FASTA → bcalm2 → read unitigs ---
  std::string tmp_dir = opt.output + "_tmp";
  fs::create_directories(tmp_dir);
  std::string diff_fa = tmp_dir + "/diff_kmers.fa";

  fprintf(stderr, "[unitig] Streaming differential k-mers to FASTA...\n");
  auto diff_stats = stream_differential_kmers_to_fasta(
      opt.bulk1_db, opt.bulk2_db, hist1, hist2,
      diff_fa, opt.min_count, opt.max_opp,
      opt.parent1_db, opt.parent2_db);
  uint32_t k = diff_stats.k;
  fprintf(stderr, "[unitig] k=%u, differential k-mers=%lu (enriched_min=%u, opposite_max=%u)\n",
          k, diff_stats.total_diff_kmers, diff_stats.enriched_min, diff_stats.opposite_max);

  if (diff_stats.total_diff_kmers == 0) {
    fprintf(stderr, "[unitig] Warning: no differential k-mers found.\n");
    fs::remove_all(tmp_dir);
    return 0;
  }

  // Run BCALM2
  std::string bcalm_prefix = tmp_dir + "/bcalm_out";
  std::string bcalm_cmd = "bcalm -in " + diff_fa
      + " -kmer-size " + std::to_string(k)
      + " -abundance-min 1"
      + " -nb-cores 4"
      + " -out " + bcalm_prefix
      + " > /dev/null 2>&1";
  fprintf(stderr, "[unitig] Running BCALM2...\n");
  int ret = std::system(bcalm_cmd.c_str());
  if (ret != 0) {
    fprintf(stderr, "[unitig] Error: BCALM2 failed (exit %d)\n", ret);
    fs::remove_all(tmp_dir);
    return 1;
  }

  // Read BCALM2 unitigs
  std::string bcalm_unitigs_fa = bcalm_prefix + ".unitigs.fa";
  auto unitigs = read_bcalm2_unitigs(bcalm_unitigs_fa, opt.min_unitig);
  fprintf(stderr, "[unitig] BCALM2 produced %zu unitigs (min_length=%u)\n",
          unitigs.size(), opt.min_unitig);

  // Clean up temp files
  fs::remove_all(tmp_dir);

  if (opt.extend && !unitigs.empty()) {
    uint32_t ext_min = std::max<uint32_t>(3, static_cast<uint32_t>(
        std::max(peak1, peak2) / 5));
    fprintf(stderr, "[unitig] Two-phase extension (min_ext_count=%u)...\n", ext_min);
    unitigs = extend_unitigs_two_phase(unitigs, k, opt.bulk1_db, opt.bulk2_db, ext_min);
    fprintf(stderr, "[unitig] Extension complete, %zu unitigs\n", unitigs.size());
  }

  // Score unitigs using KMC random access (no KmerMap needed)
  fprintf(stderr, "[unitig] Scoring unitigs (tau=%.1f)...\n", opt.tau);
  KmcRandomAccess db1_ra, db2_ra;
  if (!db1_ra.open(opt.bulk1_db))
    throw std::runtime_error("Cannot open KMC RA: " + opt.bulk1_db);
  if (!db2_ra.open(opt.bulk2_db))
    throw std::runtime_error("Cannot open KMC RA: " + opt.bulk2_db);

  auto scores = score_and_rank_unitigs_kmc(
      unitigs, k, db1_ra, db2_ra, params, static_cast<float>(opt.tau));
  db1_ra.close();
  db2_ra.close();

  // Write FASTA
  std::string fa_path = opt.output + "_unitigs.fa";
  std::ofstream fa_out(fa_path);
  if (!fa_out) {
    fprintf(stderr, "[unitig] Error: cannot open %s for writing\n", fa_path.c_str());
    return 1;
  }
  for (size_t i = 0; i < scores.size(); ++i) {
    fa_out << ">" << scores[i].id
           << " len=" << scores[i].length
           << " rank_score=" << scores[i].rank_score << "\n";
    fa_out << scores[i].sequence << "\n";
  }
  fa_out.close();

  // Write TSV
  std::string tsv_path = opt.output + "_unitigs.tsv";
  std::ofstream tsv_out(tsv_path);
  if (!tsv_out) {
    fprintf(stderr, "[unitig] Error: cannot open %s for writing\n", tsv_path.c_str());
    return 1;
  }
  tsv_out << "unitig_id\tlength\tn_kmers\tdominant_dir\tcoherence\tmean_z\t"
             "excess_per_kb\tsum_excess_mass\tsum_bulk1\tsum_bulk2\n";
  for (const auto& s : scores) {
    const char* dir = (s.dominant_dir > 0) ? "BULK1" : "BULK2";
    char buf[512];
    int n = snprintf(buf, sizeof(buf),
      "%s\t%u\t%u\t%s\t%.4f\t%.4f\t%.4f\t%.4f\t%lu\t%lu\n",
      s.id.c_str(), s.length, s.n_kmers, dir,
      s.coherence, s.mean_z, s.excess_per_kb, s.sum_excess_mass,
      s.sum_bulk1, s.sum_bulk2);
    tsv_out.write(buf, n);
  }
  tsv_out.close();

  fprintf(stderr, "[unitig] Output: %s (%zu unitigs)\n", fa_path.c_str(), scores.size());
  fprintf(stderr, "[unitig] Output: %s\n", tsv_path.c_str());

  // Optional reference mapping via minimap2 → BED output
  if (!opt.map_ref.empty()) {
    fprintf(stderr, "[unitig] Mapping unitigs to reference via minimap2: %s\n",
            opt.map_ref.c_str());

    // Score → rank_score map for BED scoring
    std::unordered_map<std::string, std::pair<float, char>> id_to_score;
    for (const auto& s : scores)
      id_to_score[s.id] = {s.rank_score, s.dominant_dir > 0 ? '+' : '-'};

    std::string paf_path = opt.output + "_unitigs.paf";
    std::string bed_path = opt.output + "_unitigs.bed";

    // minimap2 -cx asm5: precise asm-to-ref, -N 50 keep up to 50 secondary
    // -p 0.5: report secondary if score >= 50% of primary (paralog tolerance)
    std::string cmd = "minimap2 -cx asm5 -N 50 -p 0.5 -t 4 \""
        + opt.map_ref + "\" \"" + fa_path + "\" > \""
        + paf_path + "\" 2>/dev/null";
    int ret = std::system(cmd.c_str());
    if (ret != 0) {
      fprintf(stderr, "[unitig] minimap2 failed (exit %d). Skipping mapping.\n", ret);
    } else {
      // Parse PAF → BED. PAF columns:
      // qname qlen qstart qend strand tname tlen tstart tend matches alen mapq ...
      std::ifstream paf(paf_path);
      std::ofstream bed(bed_path);
      if (!paf || !bed) {
        fprintf(stderr, "[unitig] Error: cannot open PAF/BED files\n");
        return 1;
      }

      // For each query, keep only highest-score alignment(s)
      std::unordered_map<std::string, std::vector<std::string>> q_lines;
      std::string line;
      uint32_t n_lines = 0;
      while (std::getline(paf, line)) {
        if (line.empty()) continue;
        size_t tab = line.find('\t');
        if (tab == std::string::npos) continue;
        std::string qname = line.substr(0, tab);
        q_lines[qname].push_back(line);
        ++n_lines;
      }
      paf.close();

      uint32_t n_mapped = 0;
      for (auto& [qname, lines] : q_lines) {
        auto sit = id_to_score.find(qname);
        if (sit == id_to_score.end()) continue;
        for (const auto& ln : lines) {
          // Parse PAF columns
          std::vector<std::string> cols;
          size_t pos = 0, tab;
          while ((tab = ln.find('\t', pos)) != std::string::npos) {
            cols.push_back(ln.substr(pos, tab - pos));
            pos = tab + 1;
          }
          cols.push_back(ln.substr(pos));
          if (cols.size() < 12) continue;
          const std::string& tname = cols[5];
          uint64_t tstart = std::stoull(cols[7]);
          uint64_t tend = std::stoull(cols[8]);
          char strand = cols[4][0];
          char buf[512];
          int n = snprintf(buf, sizeof(buf), "%s\t%lu\t%lu\t%s\t%.1f\t%c\n",
              tname.c_str(), tstart, tend, qname.c_str(),
              static_cast<double>(sit->second.first), strand);
          bed.write(buf, n);
          ++n_mapped;
        }
      }
      bed.close();
      fprintf(stderr, "[unitig] Mapped %u alignments from %zu unitigs → %s\n",
              n_mapped, q_lines.size(), bed_path.c_str());
      // Keep .paf for inspection; user can delete
    }
  }

  return 0;
}

int main(int argc, char** argv)
{
  if (argc < 2) {
    print_usage(argv[0]);
    return 1;
  }

  if (strcmp(argv[1], "score") == 0)
    return cmd_score(argc, argv);
  if (strcmp(argv[1], "count") == 0)
    return cmd_count(argc, argv);
  if (strcmp(argv[1], "anchor") == 0)
    return cmd_anchor(argc, argv);
  if (strcmp(argv[1], "rank") == 0)
    return cmd_rank(argc, argv);
  if (strcmp(argv[1], "unitig") == 0)
    return cmd_unitig(argc, argv);

  fprintf(stderr, "Unknown command: %s\n", argv[1]);
  print_usage(argv[0]);
  return 1;
}
